### ISSUE TITLE
Automatically use password for data12.v

### ISSUE THREAD

**Issue by holly-hacker** [Leayal/VData-Reader#1]
The password for data12.v is `@PDB@?LoadBinaryVersion` (found it while reversing the game). A quick glance through the source told me you don't have it hardcoded, so perhaps adding it makes the program easier to use :)

**Comment by Leayal** [comment]
I feel illegal to put the password there (although it's not so secretly hidden).
But I'll think about a way to add "remember password" or something like that.

**Comment by holly-hacker** [comment]
I'm pretty sure it's not illegal to add it, although that depends on the country you live in. If you really don't want to hardcode it, you can also just have instructions on where to find it.

**Comment by Leayal** [comment]
I've added the password history so you don't have to going around to find the password anymore.
Instead, click the dropdown button and select one of the passwords you have used (successfully).

This should work in long term (unless LionGames decide to change the way they pack the file or their encryption), instead of hardcoded the password into a tool that is no longer maintained.

Cheers~!

**Comment by holly-hacker** [comment]
Looks good. Thanks!
